import Head from "next/head";
import { useRef } from "react";

import Benchmarks from "@/components/Benchmarks";
import EmailForm from "@/components/EmailForm";
import Faq from "@/components/Faq";
import Features from "@/components/Features";
import Hero from "@/components/Hero";
import styles from "@/styles/Home.module.css";

export default function Home() {
  const benchmarkRef = useRef<HTMLDivElement>(null);

  return (
    <>
      <Head>
        <title>Solorbit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EmailForm />
      <main className={styles.main}>
        <Hero scrollDownRef={benchmarkRef} />
        <Benchmarks ref={benchmarkRef} />
        <Features />
        <Faq />
      </main>
    </>
  );
}
